server:
  port: 8701

eureka:
  instance:
    hostname: localhost #for 192.168.100.63
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.100.61:8501/eureka/,http://192.168.100.61:8601/eureka/

spring.cloud.config.discovery.enabled: true